### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by janneyow** [arthurfenderbucker/LaTTe-Language-Trajectory-TransformEr#1]
Thanks for sharing your scripts! I'm trying to run them but couldn't find the following:
1. "4D_100k_scaping_factor" data
2. Image dataset
3. Training data to generate preprocessed data

Do you mind sharing these data as well? Thanks!

**Comment by arthurfenderbucker** [comment]
Hi, thank you for noticing.
I just uploaded the image dataset and "4D_100k_scaping_factor" , please check the README updates and download synthetic dataset again.
The training data to generate the preprosses data is located at the files with "data_" prefix

**Comment by janneyow** [comment]
Thanks for the update! I don't have access to the image dataset on your drive, could you update the permissions? 

Thanks in advance! :)
