### ISSUE TITLE
Has anyone really run this code successfully?Can we discuss this together with everyone?

### ISSUE THREAD

**Issue by zxb-0** [arthurfenderbucker/LaTTe-Language-Trajectory-TransformEr#3]

**Comment by Bailey-24** [comment]
Wechat: Jiahui_Zhu_
I didn't run it, but we can talk about this.

**Comment by arthurfenderbucker** [comment]
Hi @zxb-0, I would be happy to help you to run the code. Do you have any doubts or are you facing any specific issues?

**Comment by zxb-0** [comment]
i can not find this package -- my_interfaces.msg 
and Can you share with me the code in coppeliasim, the code that controls the movement of the robot.thank you.

**Comment by zxb-0** [comment]
> 微信：Jiahui_Zhu_我没有运行它，但我们可以谈谈这个。

how can i chat with you?

**Comment by zxb-0** [comment]
> 嗨，我很乐意帮助您运行代码。您有任何疑问或面临任何具体问题吗？

![2d4a79b3-0d96-4364-96c8-4041987c41fa](https://github.com/arthurfenderbucker/LaTTe-Language-Trajectory-TransformEr/assets/97783815/0b9544b3-85d4-481f-aca1-7420018841cd)


Following the readme approach, there are many matrix shape mismatch errors in the interactive.py. Does the project have an operation manual, I can't understand it. Because there are no comments. The readme in github is too simple, can you tell us more about the process of the project?
