### ISSUE TITLE
Access Denied on synthetic dataset links

### ISSUE THREAD

**Issue by anurag-overfits** [arthurfenderbucker/LaTTe-Language-Trajectory-TransformEr#5]
Hii
I'm unable to access the dataset links now. I think the links are available only on the institutional ID used to create the drive links.

**Comment by Brain1920** [comment]
I came with the same problem.The connections of models,synthetic dataset and image dataset are aborted.And if directly use the links on google,found 404.

**Comment by arthurfenderbucker** [comment]
Hi, I apologize for the delay, I just updated the dataset links. It should be working now.
